service: members

provider:
  name: google
  stage: ${opt:stage, "dev"}
  runtime: nodejs12
  project: ${env:GCP_PROJECT, "sda-dev-277804"}
  credentials: ~/.gcloud/sda-dev-277804.json

custom:
  base: ${self:service}-${self:provider.stage}

plugins:
  - serverless-google-cloudfunctions
  - serverless-webpack

functions:
  create-member-db:
    # handler: generate
    events:
      - event:
          eventType: providers/cloud.firestore/eventTypes/member.create
          resource: 'projects/${self:provider.project, ""}/databases/(default)/documents/branches/sa/members/{memberId}'
